HPARAMS="
dataset=celebA,\
measurement_type=drop_independent,\
drop_prob=0.0,\
patch_size=32,\
blur_radius=1.0,\
blur_filter_size=5,\
additive_noise_std=0.0,\
num_angles=1,\
\
train_mode=ambient,\
unmeasure_type=None,\
\
model_class=unconditional,\
model_type=dcgan,\
z_dim=100,\
z_dist=uniform,\
gp_lambda=10.0,\
d_ac_lambda=1.0,\
g_ac_lambda=0.1,\
\
opt_type=adam,\
batch_size=64,\
g_lr=0.0002,\
d_lr=0.0002,\
lr_decay=false,\
opt_param1=0.5,\
opt_param2=0.999,\
g_iters=2,\
d_iters=1,\
\
results_dir=./results/,\
sample_num=64,\
max_checkpoints=1,\
max_train_iter=70000,\
"

python src/main.py \
    --hparams $HPARAMS
